### ISSUE TITLE
error on script

### ISSUE THREAD

**Issue by ghost** [JeffreyHyer/auto-coc#1]
hi im new on github and want to test your script but i have error when i execute your script this is the error show when i execute the script
name_error
cocWindow = App("Bluestacks").window(0)
cocSidebar = Region((cocWindow.x + 6), (cocWindow.y + 185), 468, 690)
can you explain how can i fix this thanks in advance...

**Comment by JeffreyHyer** [comment]
That error indicates you're missing a class/module. In this case it is probably 'App' and 'Region' because those are imported from the SikuliX library.

I will add instructions shortly on setting up SikuliX and running the script from both the IDE and the command line (depending on which method you prefer).

**Comment by ghost** [comment]
ok thank you..

**Comment by JeffreyHyer** [comment]
@bushido-21 Please see the updated [README](https://github.com/jeffreyhyer/auto-coc#initial-setup) for setup/installation and usage instructions. If you have any trouble following them please let me know :)

**Comment by ghost** [comment]
ok thank you very much i try it when i get home i realy appreciate your help and quick response..thanks again

**Comment by ghost** [comment]
hi there i just fallow the instruction but its not working i dont know what is the problem ... :( i try to use  plz can you give more info like what resulution should i use and thanks :) i just open on sikuli but automaticaly shutdown the scripter thanks again

**Comment by JeffreyHyer** [comment]
@bushido-21 Sorry you're having trouble with it. Try running it via the command line and report what the error is (sometimes Sikuli doesn't tell you what the error was).

Also you may need to update the images to match against for your computer. They are very sensitive so what matches on my machine won't always work on other machines.

I use 1920x1080 resolution with BlueStacks in windowed mode (not full screen)
