### ISSUE TITLE
sikuli ide crashes

### ISSUE THREAD

**Issue by ghost** [JeffreyHyer/auto-coc#2]
i fallow the instruction option 1 open in sikuli but it crashes and i try to command prompt but i get error filename not specify or syntax error something like that i dont really remember the exactly show in terminal... :( i hope you can help me thanks again

**Comment by JeffreyHyer** [comment]
@bushido-21 If you can tell me what the error was (from the command line) I can try to help you better.

Also I've pushed some changes to the script so try downloading the latest version and running it.

**Comment by ghost** [comment]
thank you very much i try on sikuli ide when i open it to sikuli ide it will automaticaly close the sikuli ide and when i try on command prompt this is the error show
the filename, directory name , or volume label syntax is incorrect. :( btw im realy appreciate your time thanks again :)

**Comment by JeffreyHyer** [comment]
It sounds like Sikuli IDE is having an issue with your computer configuration/setup. I'm not sure how to help you without more information. I don't think it's my script that is having the issue as I've run it on several machines now without problems, including from a clean install of Sikuli and Python. I could be wrong though.

**Comment by cybman** [comment]
is happening the same with me

c:\cocbot_sikuli>runIDE -r c:/auto-coc.sikuli
+++ running this Java
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) Client VM (build 24.51-b03, mixed mode, sharing)
+++ trying to start Sikuli IDE
+++ using: -Xms64M -Xmx512M -Dfile.encoding=UTF-8 -Dsikuli.FromCommandLine -jar
c:\cocbot_sikuli\sikuli-ide.jar -r c:/auto-coc.sikuli
[error] FileManager: Script folder c:\auto-coc.sikuli does not contain a script
file named auto-coc.xxx
[error] Terminating SikuliX after a fatal error! Sorry, but it makes no sense to
 continue!

**Comment by JeffreyHyer** [comment]
Try renaming the file "attack-and-rebuild-troops.py" to "auto-coc.py", that should fix it. The file and the folder need to have the same name.
