### ISSUE TITLE
script load but nothing happen

### ISSUE THREAD

**Issue by ghost** [JeffreyHyer/auto-coc#4]
hi there the sikuli ide load the script but nothing happen and in the cmd there was error show here:

+++ running this Java
java version "1.7.0_76"
Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)
+++ trying to start Sikuli IDE
+++ using: -Xms64M -Xmx512M -Dfile.encoding=UTF-8 -Dsikuli.FromCommandLine -jar
C:\Users\xxxxxx\Desktop\sikuli\sikuli-ide.jar
Jan 25, 2015 10:48:06 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0
x80000002. Windows RegCreateKeyEx(...) returned error code 5.

i use this script on TH6 i hope you can help me thanks again

**Comment by ghost** [comment]
hi there i fix the cmd error but still not work the script can i try latest version of sikuli to see if working or not thanks

**Comment by cybman** [comment]
open the script usint the command prompt, there you can see all the errors from the script

**Comment by sadiqkassamali** [comment]
i am receiving this error.

C:\Users\sskassamali\Downloads\boo>runIDE.cmd -r /auto-coc-master.sikuli -s
+++ running this Java
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
+++ trying to start Sikuli IDE
+++ using: -Xms64M -Xmx512M -Dfile.encoding=UTF-8 -Dsikuli.FromCommandLine -jar
C:\Users\sskassamali\Downloads\boo\sikuli-ide.jar -r /auto-coc-master.sikuli -s
[error] FileManager: Not a valid Sikuli script: C:\auto-coc-master.sikuli
[error] Terminating SikuliX after a fatal error! Sorry, but it makes no sense to
 continue!
If you do not have any idea about the error cause or solution, run again
with a Debug level of 3. You might paste the output to the Q&A board.

**Comment by darrensapalo** [comment]
@sadiqkassamali You need to rename the `attack-and-rebuild-troops.py` file to `auto-coc-master.sikuli`. The folder name must be the same as the python file.
