### ISSUE TITLE
unable to load script

### ISSUE THREAD

**Issue by sadiqkassamali** [JeffreyHyer/auto-coc#7]
Hi i am receiving this error

C:\Users\sskassamali\Downloads\boo>runIDE.cmd -r /auto-coc-master.sikuli -s
+++ running this Java
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
+++ trying to start Sikuli IDE
+++ using: -Xms64M -Xmx512M -Dfile.encoding=UTF-8 -Dsikuli.FromCommandLine -jar
C:\Users\sskassamali\Downloads\boo\sikuli-ide.jar -r /auto-coc-master.sikuli -s
[error] FileManager: Not a valid Sikuli script: C:\auto-coc-master.sikuli
[error] Terminating SikuliX after a fatal error! Sorry, but it makes no sense to
 continue!
If you do not have any idea about the error cause or solution, run again
with a Debug level of 3. You might paste the output to the Q&A board.

**Comment by JeffreyHyer** [comment]
You'll need to change the name of the python script from 'attack-and-rebuild-troops.py' to 'auto-coc.py'.

See #3

**Comment by sadiqkassamali** [comment]
it works, thanks
