### ISSUE TITLE
unable to attack if i define the min gold and elixir 

### ISSUE THREAD

**Issue by sadiqkassamali** [JeffreyHyer/auto-coc#8]
Hi Jeffery;

can you check my script and see what i am doing wrong now, i am able to attack fine if i set the gold and elixir to 0 but as soon as i change the number it doesn't seem to find it.

_[Removed code for brevity]_

**Comment by JeffreyHyer** [comment]
You probably need to update the number images (png files) within the numberOCR() function.

When you set the min gold and elixir it tries to read the screen to determine how much gold and elixir is available and only attack if it's above the threshold you set. But if it can't read the numbers it won't work.
