### ISSUE TITLE
Script doesn't start

### ISSUE THREAD

**Issue by saber00** [JeffreyHyer/auto-coc#9]
Hi, great work on the script, but somehow its not working for me :/. Whenever I start the script with bluestacks open, I get the error:
[log] App.focus C:\Program Files\BlueStacks\HD-StartLauncher.exe(0) #0

[+] Idle Check
[error] script [ auto-coc ] stopped with error in line 782
[error] AttributeError ( 'bool' object has no attribute 'exists' )
[error] --- Traceback --- error source first line: module ( function ) statement 633: main ( checkIdle ) if (cocWindow.exists("1420184045669.png", 0)):
[error] --- Traceback --- end --------------

**Comment by JeffreyHyer** [comment]
That error is a result of the script not being able to find the BlueStacks window. Check the path to BlueStacks (C:\Program Files\BlueStacks\HD-StartLauncher.exe) and make sure it's correct in the script. If not update it to the path of your executable and run it again.

Alternatively, you can insert the following line into the script on or around line 8 (after the imports, before the `timestamps` variable.

``` python
cocWindow = App("Bluestacks").window(0)
```
